---
title: "Katja Karhi Thesis 2024 - Vinca minor"
output: html_notebook
---
##LIBRARY
```{r Library}
library(tidyverse) 
library(effects)
library(plotrix) 
library(vegan)
library(fitdistrplus)
library(raster) 
library(lmodel2) 
library(lme4) 
#library(Hmisc)
library(plyr)
detach(package:plyr)
detach(package:dplyr)
library(ape) 
library(nlme)
library(sm) 
library(car) 
library(smatr)
library(scatterplot3d) 
library(lsmeans) 
#library(psych)

library(MuMIn) 
library(outliers) 
library(dplyr) 
library(devtools) 
library(FactoMineR) 
library(factoextra) 
library(ade4) 
library(cluster)
library(GGally) 
library(ggplot2) 
library(multcomp) 
library(pairwiseAdonis)
library(RColorBrewer)
library(ggbiplot)
```

##CHAPTER 1
```{r Simpsons/Shannons Diversity Calculations DFs}
data=read_csv("fieldalgomaupercentcover.csv", na="?")
attach(data)
summary(data)

ddply(data,~plot.year,function(x)+ data.frame(RICHNESS=sum(x[-1]>0)))
 ddply(data,~plot.year,function(x)+ data.frame(ABUNDANCE=sum(x[-1])))

ddply(data,~plot.year,function(x)
+         data.frame(SHANNON=diversity(x[-1], index="shannon"))
)
shannonplot<-diversity(data[-1], index="shannon")
shannonplot
plot(shannonplot)

simpsonplot<-diversity(data[-1], index="simpson")
simpsonplot
plot(simpsonplot)

```
```{r Diversity Analysis Using Percent Cover}
library(tidyverse)
data=read_csv("fieldalgomaupercentcoverdiversitycalculations.csv", na="?")
attach(data)
data
str(data)
summary(data)

#check data is numeric
is.numeric(data$simpsonsdiversity)
data
 
#check for assumptions
shapiro.test(simpsonsdiversity)
shapiro.test(logsimpson)
shapiro.test(shannondiversity)
shapiro.test(logshannon)

#Simpson's Test
library(dunn.test) 

kruskal_result <- kruskal.test(simpsonsdiversity ~ treatment, data = data) 
print(kruskal_result) 
 
if (kruskal_result$p.value < 0.05) {    
  posthoc_result <- dunn.test(data$simpsonsdiversity, g = data$treatment, method = "bonferroni")   
 
print(posthoc_result) }

#Shannon Test
kruskal_result <- kruskal.test(shannondiversity ~ treatment, data = data) 
print(kruskal_result) 
if (kruskal_result$p.value < 0.05) {   
  posthoc_result <- dunn.test(data$simpsonsdiversity, g = data$treatment, method = "bonferroni")   
print(posthoc_result) }


#Boxplots for Simpson's diversity
#By year 
simpsonsdiversity <- ggplot(data, aes(x = year, y = simpsonsdiversity, fill = year)) +
  geom_boxplot() +
  theme_classic() +
  labs(
    x = "Year",
    y = "Simpsons Diversity",
    title = "Simpsons Diversity AlgomaU Field"
  ) +
  ylim(0, 1) +
  scale_fill_brewer(palette = "GnBu") +  # Use the "Greens" palette directly
  theme(
    plot.title = element_text(hjust = 0.5),  # Center the title
    axis.title.x = element_text(vjust = -0.5),  # Adjust X-axis title position
    axis.title.y = element_text(vjust = -0.5)  # Adjust Y-axis title position
  )
simpsonsdiversity
#By invasion treatment 
simpsonsdiversityinvasion <- ggplot(data, aes(x = treatment, y = simpsonsdiversity, fill = treatment)) +
  geom_boxplot() +
  theme_classic() +
  labs(
    x = "Plot Type",
    y = "Simpsons Diversity",
    title = "Simpsons Diversity AlgomaU Field"
  ) +
  ylim(0, 1) +
  scale_fill_brewer(palette = "GnBu") +  # Use the "Greens" palette directly
  theme(
    plot.title = element_text(hjust = 0.5),  # Center the title
    axis.title.x = element_text(vjust = -0.5),  # Adjust X-axis title position
    axis.title.y = element_text(vjust = -0.5)  # Adjust Y-axis title position
  )
simpsonsdiversityinvasion
```
```{r Field Differences for Maples Only}

data=read_csv("fieldalgomaupercentcovernmds.csv", na="?")

head(data)
library(car)
library(dunn.test)

# Check normality
shapiro_test <- shapiro.test(data$Acer.saccharum)
print(shapiro_test)

#ANOVA/KRUSKAL TEST
if (shapiro_test$p.value > 0.05 && levene_test$`Pr(>F)`[1] > 0.05) {
  anova_result <- aov(Acer.saccharum ~ treatment, data = data)
  print(summary(anova_result))
  
  if (summary(anova_result)[[1]]["Pr(>F)"][1] < 0.05) {
    print(TukeyHSD(anova_result))
  }
} else {
  kruskal_result <- kruskal.test(Acer.saccharum ~ treatment, data = data)
  print(kruskal_result)
  if (kruskal_result$p.value < 0.05) {
    dunn_result <- dunn.test(data$Acer.saccharum, data$treatment, method = "bonferroni")
    print(dunn_result)
  }
}

summary_stats <- aggregate(Acer.saccharum ~ treatment, data = data, 
                           FUN = function(x) c(mean = mean(x), std_error = std.error(x)))

summary_stats_df <- data.frame(
  treatment = summary_stats$treatment,
  mean = summary_stats$Acer.saccharum[, "mean"],
  std_error = summary_stats$Acer.saccharum[, "std_error"]
)

print(summary_stats_df)

```
```{R Field - NMDS Plots}

data=read_csv("fieldalgomaupercentcovernmds.csv", na="?")
print(data)
any(is.na(data)) 

#metaMDS does not work with NAs in the dataset. Also a good idea to remove samples with no reads
ord <- metaMDS(data[ ,4:36])  
ord

#change for the columns you use
data$nmds1 <- ord$points[,1]
data$nmds2 <- ord$points[,2]
attach(data)
nmds1

results <- with(data, adonis(vegdist(data[ ,4:36]) ~ treatment, permutations =999,method = "bray")) #PERMANOVA coding
results

outlier(nmds1)

pairwise.adonis2(data[,4:36]~treatment, data=data) #dont run if not significant

#NMDS Plot
my_colors <- c("Uninvaded" = "grey", "Edge" = "darkgreen", "Invaded" = "cadetblue")

finalplot <- ggplot(data, aes(x = nmds1, y = nmds2, color = factor(treatment, levels = c("uninvaded", "edge", "invaded"), labels = c("Uninvaded", "Edge", "Invaded")), shape = factor(year))) +
  geom_point() +
  # Ensure stat_ellipse uses the new factor levels correctly; might need adjustment if it doesn't work as expected
  stat_ellipse(data = filter(data, treatment == "uninvaded"), aes(group = treatment), color = "grey") +
  stat_ellipse(data = filter(data, treatment == "edge"), aes(group = treatment), color = "darkgreen") +
  stat_ellipse(data = filter(data, treatment == "invaded"), aes(group = treatment), color = "cadetblue") +
  # Apply the updated color definitions ensuring they match the new labels
  scale_color_manual(values = my_colors) +
  theme_classic() +
  annotate("text", x = Inf, y = Inf, label = expression("PERMANOVA: F"[2*","*50] == "20.37, P = 0.001, R² = 0.45"), hjust = 1, vjust = 1, size = 3.5) +
  annotate("text", x = Inf, y = Inf, label = "STRESS = 0.14", hjust = 1, vjust = 2.5, size = 3.5) +
  # Remove legend title
  labs(color = NULL) +
  # Set shape labels
  scale_shape_manual(values = c("2020" = 1, "2023" = 2))

finalplot <- finalplot +
  labs(color = "Plot Type", shape = "Year")

finalplot
```
```{r Field - Nutrients}
#emmeans(model, list(pairwise ~ treatment), adjust = "tukey") #posthoc

#TukeyHSD(aov(shannondiversity ~ year*treatment, data=data))
#summary (model)
library(tidyverse)

data=read_csv("fieldsoilnutrients.csv", na="?")
library(rstatix)
library(emmeans)
library(plotrix)
# Model 1
shapiro_test(data, Phosphorus_Bicarb)
shapiro_test(data, logPhosphorus_Bicarb)

model1 <- aov(Phosphorus_Bicarb ~ plottype, data=data)
anova(model1)

model1b <- aov(logPhosphorus_Bicarb ~ plottype, data=data)
anova(model1b)

# Model 2
shapiro_test(data, Organic_Matter)
shapiro_test(data, logOrganic_Matter)

model2 <- aov(logOrganic_Matter ~ plottype, data=data)
summary(model2)
anova(model2)

# Model 3
shapiro_test(data, PBray)
shapiro_test(data, logPBray)

model3 <- aov(logPBray ~ plottype, data=data)
summary(model3)
anova(model3)

# Model 4
shapiro_test(data, Potassium)

model4 <- aov(Potassium ~ plottype, data=data)
summary(model4)
anova(model4)

# Model 5
shapiro_test(data, Magnesium)

model5 <- aov(Magnesium ~ plottype, data=data)
summary(model5)
anova(model5)

#SIGNIFICANT MODEL
shapiro_test(data, Calcium)

model6 <- aov(Calcium ~ plottype, data=data)
summary(model6)
anova(model6)

calcium.df <- data %>%
  group_by(plottype) %>%
  summarise(
    sd = std.error(Calcium, na.rm = TRUE),
    numberleaves = mean(Calcium, na.rm = TRUE)
  )
TukeyHSD(aov(Calcium~ plottype, data = data)) 

summary (model1)


# Model 7
shapiro_test(data, Sodium)

model7 <- aov(Sodium ~ plottype, data=data)
summary(model7)
anova(model7)

# Model 9
shapiro_test(data, CEC_meq)

model9 <- aov(CEC_meq ~ plottype, data=data)
summary(model9)
anova(model9)

# Model 10
shapiro_test(data, K)
model10 <- aov(K ~ plottype, data=data)
summary(model10)
anova(model10)

# Model 11
shapiro_test(data, h)

model11 <- aov(h ~ plottype, data=data)
summary(model11)
anova(model11)

shapiro_test(data, mg)

model12 <- aov(mg ~ plottype, data=data)
summary(model12)
anova(model12)

shapiro_test(data, logca)

model12 <- aov(logca ~ plottype, data=data)
summary(model12)
anova(model12)
emmeans(model12, list(pairwise ~ plottype), adjust = "tukey")

# Model 12
shapiro_test(data, na)

model12 <- aov(logna ~ plottype, data=data)
summary(model12)
anova(model12)

#SIGNIFICANT MODEL SULFUR
shapiro_test(data, S_ppm)
             
model13 <- aov(S_ppm ~ plottype, data=data)
summary(model13)
anova(model13)
emmeans(model13, list(pairwise ~ plottype), adjust = "tukey")


S_ppm.df <- data %>%
  group_by(plottype) %>%
  summarise(
    sd = std.error(S_ppm, na.rm = TRUE),
    numberleaves = mean(S_ppm, na.rm = TRUE)
  )

# Model 14
shapiro_test(data, logZn_ppm)
             
model14 <- aov(Zn_ppm ~ plottype, data=data)
summary(model14)
anova(model14)

# Model 15
shapiro_test(data, logMn_ppm)

model15 <- aov(Mn_ppm ~ plottype, data=data)
summary(model15)
anova(model15)

# Model 16
shapiro_test(data,Fe_ppm)

model16 <- aov(Fe_ppm ~ plottype, data=data)
summary(model16)
anova(model16)

# Model 17
shapiro_test(data, logCu_ppm)
             
model17 <- aov(Cu_ppm ~ plottype, data=data)
summary(model17)
anova(model17)

# Model 18


# Model 19
shapiro_test(data, Saturation_p_percent)

model19 <- aov(Saturation_p_percent ~ plottype, data=data)
summary(model19)
anova(model19)

# Model 20
shapiro_test(data, Al_ppm)

model20 <- aov(Al_ppm ~ plottype, data=data)
summary(model20)
anova(model20)

# Model 21
shapiro_test(data, Saturation_Al_percent)

model21 <- aov(Saturation_Al_percent ~ plottype, data=data)
summary(model21)
anova(model21)

# Model 22
shapiro_test(data, K_Mg_Ratio)
             
model22 <- aov(K_Mg_Ratio ~ plottype, data=data)
summary(model22)
anova(model22)

# Model 23
shapiro_test(data, logENR)
shapiro_test(data, ENR)
             
model23 <- aov(ENR ~ plottype, data=data)
summary(model23)
anova(model23)

#model23
shapiro_test(data, CN_ratio)
             
Model24 <- aov(CN_ratio ~ plottype, data=data)
anova(Model24)

#non normal data
# Model 8
shapiro_test(data, logpH)
shapiro_test(data, pH)
kruskal_test_result <- kruskal.test(pH ~ plottype, data = data)
print(kruskal_test_result)

shapiro_test(data, logENR)
shapiro_test(data, ENR)
kruskal_test_result2 <- kruskal.test(ENR ~ plottype, data = data)
print(kruskal_test_result2)


shapiro_test(data, logB_ppm)
shapiro_test(data, B_ppm)
kruskal_test_result3 <- kruskal.test(B_ppm ~ plottype, data = data)
print(kruskal_test_result3)



S_ppm.df
calcium.df
```

##CHAPTER 2
```{r Pot Diversity - Percent Cover}
library(plyr)


#percent cover 
data=read_csv("percentcoverpot.csv", na="?")
attach(data)

ddply(data,~potid,function(x)+ data.frame(RICHNESS=sum(x[-1]>0)))
 ddply(data,~potid,function(x)+ data.frame(ABUNDANCE=sum(x[-1])))

ddply(data,~potid,function(x)
+         data.frame(SHANNON=diversity(x[-1], index="shannon"))
)

plot(simpsonplot)


data=read_csv("potdiversitycalculations.csv", na="?")
attach(data)

library(readr)
library(car)
library(dunn.test)

#simpsons percent
shapiro.test(simpsonsdiversitypercent)
model<-aov(simpsonsdiversitypercent ~ shade*invasion , data=data)
model
Anova(model, type="III")
TukeyHSD(model)
```
```{r Principal Component analysis}

data=read_csv("growthtracking.csv", na="?")
attach(data)
str(data)
data
print(data)
# MAPLE
maple_data <- subset(data, speciesid %in% c("maple"))
maple_data

maple_data2<-subset(maple_data,graphdate=="10-Jul")
maple_data2

dfdata <- maple_data2 %>%
  group_by(potid, sampledate, shadetreatment, invasiontreatment, treatment
) %>%
  summarise(
    leaflength = mean(longestleaflength_cm, na.rm = TRUE),
    height = mean(height_cm, na.rm = TRUE),
    numberofleaves = mean(num_leaves, na.rm = TRUE)
  )
dfdata

#HEMPNETTLE
hempnettledata1 <- subset(data, speciesid %in% c("hempnettle"))
hempnettledata1

hempnettledata<-subset(hempnettledata1,graphdate=="10-Jul")
hempnettledata

hempnettledataf <- hempnettledata %>%
  group_by(potid, sampledate, shadetreatment, invasiontreatment, treatment
) %>%
  summarise(
    leaflength = mean(longestleaflength_cm, na.rm = TRUE),
    height = mean(height_cm, na.rm = TRUE),
    numberofleaves = mean(num_leaves, na.rm = TRUE)
  )
hempnettledataf

##BINDWEED
bindweeddata1 <- subset(data, speciesid %in% c("bindweed"))
bindweeddata1

bindweeddata<-subset(bindweeddata1,graphdate=="10-Jul")
bindweeddata

bindweeddataf <- bindweeddata %>%
  group_by(potid, sampledate, shadetreatment, invasiontreatment, treatment
) %>%
  summarise(
    leaflength = mean(longestleaflength_cm, na.rm = TRUE),
    height = mean(height_cm, na.rm = TRUE),
    numberofleaves = mean(num_leaves, na.rm = TRUE)
  )
bindweeddataf
print(bindweeddataf)

#PCA PLOTS
library(ggbiplot)
library(pairwiseAdonis)
library(FactoMineR) 
library(factoextra)

#MAPLE
dfdata<- na.omit(dfdata)
dfdata
traits.1 =  dfdata[,6:8]
traits.1
cor(traits.1) 
traits.pc = traits.1 %>% 
  princomp(cor=T) 
summary(traits.pc) 
ggscreeplot(traits.pc) 
biplot(traits.pc)

set.seed(19900730) 

results11 <- with(dfdata, adonis(vegdist(dfdata[ ,6:8]) ~ shadetreatment * invasiontreatment, permutations =999,method = "bray")) 
results11

results <- pairwise.adonis2(dfdata[, 6:8] ~ shadetreatment * invasiontreatment, data=dfdata)
results


T1 <- fviz_pca_biplot(  
  traits.pc,   geom = "point",   
  pointshape = 16, 
  label = "all",  
  fill.ind = dfdata$treatment,   
  addEllipses = TRUE,  
  ellipse.type ="confidence",   
  ellipse.level = 0.95,  
  col.ind = dfdata$treatment,   
  ellipse.col = dfdata$treatment,   
  col.var = "black",   
  repel = TRUE,   
  legend.title = "Treatment (ShadeInvasion)",    
  ggtheme = theme_classic() ) + ggtitle("Acer spp.") + 
  theme(plot.title = element_text(face = "italic"))

T1

#HEMPNETTLE 
hempnettledataf<- na.omit(hempnettledataf)
traits.2 =  hempnettledataf[,6:8]
traits.2
cor(traits.2) 
traits.pc2 = traits.2 %>% 
  princomp(cor=T) 
summary(traits.pc2) 
ggscreeplot(traits.pc2) 
biplot(traits.pc2)

set.seed(19900730) 

results21 <- with(hempnettledataf, adonis(vegdist(hempnettledataf[ ,6:8]) ~ shadetreatment * invasiontreatment, permutations =999,method = "bray")) 
results21

results2 <- pairwise.adonis2(hempnettledataf[, 6:8] ~ invasiontreatment, data=hempnettledataf)
results2


T2 <- fviz_pca_biplot(  
  traits.pc2,   geom = "point",   
  pointshape = 16, 
  label = "all",  
  fill.ind = hempnettledataf$treatment,   
  addEllipses = TRUE,  
  ellipse.type ="confidence",   
  ellipse.level = 0.95,  
  col.ind = hempnettledataf$treatment,   
  ellipse.col = hempnettledataf$treatment,   
  col.var = "black",   
  repel = TRUE,   
  legend.title = "Treatment (ShadeInvasion)",    
  ggtheme = theme_classic() ) + ggtitle("Galeopsis tetrahit") + 
  theme(plot.title = element_text(face = "italic"))

T2

#BINDWEED
bindweeddataf<- na.omit(bindweeddataf)
traits.3 =  bindweeddataf[,6:8]
traits.3
cor(traits.3) 
traits.pc3 = traits.3 %>% 
  princomp(cor=T) 
summary(traits.pc3) 
ggscreeplot(traits.pc3) 
biplot(traits.pc3)

set.seed(19900730) 

results31 <- with(bindweeddataf, adonis(vegdist(bindweeddataf[ ,6:8]) ~ shadetreatment * invasiontreatment, permutations =999,method = "bray")) 
results31

results3 <- pairwise.adonis2(bindweeddataf[, 6:8] ~ shadetreatment*invasiontreatment, data=bindweeddataf)
results3

bindweeddataf$treatment <- factor(bindweeddataf$treatment, 
                                  levels = c("earlyinvaded", "earlyuninvaded", "controlinvaded", "controluninvaded", "normalinvaded", "normaluninvaded"), 
                                  labels = c("Early/Invaded", "Early/Uninvaded", "Control/Invaded", "Control/Uninvaded", "Normal/Invaded", "Normal/Uninvaded"))

T3 <- fviz_pca_biplot(
  traits.pc3,
  geom = "point",
  pointshape = 16,
  label = "all",
  fill.ind = bindweeddataf$treatment, # Ensure this is a factor with the new level names
  addEllipses = TRUE,
  ellipse.type = "confidence",
  ellipse.level = 0.95,
  col.ind = bindweeddataf$treatment, # Ensure this is the same factor
  ellipse.col = bindweeddataf$treatment, # Same here
  col.var = "black",
  repel = TRUE,
  legend.title = "Treatment (ShadeInvasion)",
  ggtheme = theme_classic()
) + ggtitle("Fallopia cilinodis") +
  theme(plot.title = element_text(face = "italic")) +
  scale_color_discrete(name = "Treatment (Shade/Invasion)") +
  scale_fill_discrete(name = "Treatment (Shade/Invasion)")  # This should now work with your new factor levels

T3
T1
T2

library(patchwork)

# Use the `&` operator to denote the plots should be plotted together
combined_plot <- (T1 / T2 / T3) + 
                 plot_layout(guides = 'collect') & 
                 theme(legend.position = 'bottom')

# The `guides = 'collect'` argument specifies that the legends should be collected into one single legend
# `theme(legend.position = 'bottom')` ensures that the collected legend is placed at the bottom

# To remove legends from T1 and T2 but keep T3's, you can do the following:
T1 <- T1 + theme(legend.position = "none")
T2 <- T2 + theme(legend.position = "none")
# T3 will retain its legend by default

# Now combine them again
combined_plot <- T1 + T2 + T3 + plot_layout(guides = 'collect')
# Save the combined plot, adjust the width and height as needed for your specific size requirements
ggsave("PCAPLOTTHESIS.png", combined_plot, width = 16, height = 5, dpi = 300)

```
```{r Growth Tracking - Acer}

data=read_csv("growthtracking.csv", na="?")
attach(data)
str(data)

temp.data <- subset(data, speciesid=="maple")
temp.data

temp.data2<-subset(temp.data,graphdate=="10-Jul")
temp.data2
#using this code to get the means and std error for the tables 
tempdata1 <- subset(temp.data2, treatment=="controluninvaded") 
tempdata1
mean(tempdata1$num_leaves, na.rm=TRUE) 
std.error(tempdata1$num_leaves, na.rm=TRUE)

shapiro.test(temp.data2$lognum_leaves)

model1<-lmer(lognum_leaves ~ shadetreatment*invasiontreatment + (1|potid), data = temp.data2)
model1 
Anova(model1)

# Perform Tukey HSD test for shadetreatment * invasiontreatment interaction
emm_interaction <- emmeans(model1, ~ shadetreatment * invasiontreatment)
tukey_interaction <- pairs(emm_interaction, adjust = "tukey")
print("Tukey HSD results for shadetreatment * invasiontreatment interaction:")
print(tukey_interaction)

# Perform Tukey HSD test for shadetreatment
emm_shade <- emmeans(model1, ~ shadetreatment)
tukey_shade <- pairs(emm_shade, adjust = "tukey")
print("Tukey HSD results for shadetreatment:")
print(tukey_shade)

# Perform Tukey HSD test for invasiontreatment
emm_invasion <- emmeans(model1, ~ invasiontreatment)
tukey_invasion <- pairs(emm_invasion, adjust = "tukey")
print("Tukey HSD results for invasiontreatment:")
print(tukey_invasion)

```
```{r Growth Tracking - Hempnettle}

data=read_csv("growthtracking.csv", na="?")
attach(data)
str(data)

temp.data <- subset(data, speciesid=="hempnettle")
temp.data

temp.data2<-subset(temp.data,graphdate=="10-Jul")
temp.data2
#using this code to get the means and std error for the tables 
tempdata1 <- subset(temp.data2, treatment=="earlyinvaded") 
tempdata1
mean(tempdata1$longestleaflength_cm, na.rm=TRUE) 
std.error(tempdata1$longestleaflength_cm, na.rm=TRUE)

shapiro.test(temp.data2$longestleaflength_cm)

model1<-lmer(longestleaflength_cm ~ shadetreatment*invasiontreatment + (1|potid), data = temp.data2)
model1 
Anova(model1, type="III")

# Perform Tukey HSD test for shadetreatment * invasiontreatment interaction
emm_interaction <- emmeans(model1, ~ shadetreatment * invasiontreatment)
tukey_interaction <- pairs(emm_interaction, adjust = "tukey")
print("Tukey HSD results for shadetreatment * invasiontreatment interaction:")
print(tukey_interaction)

# Perform Tukey HSD test for shadetreatment
emm_shade <- emmeans(model1, ~ shadetreatment)
tukey_shade <- pairs(emm_shade, adjust = "tukey")
print("Tukey HSD results for shadetreatment:")
print(tukey_shade)

# Perform Tukey HSD test for invasiontreatment
emm_invasion <- emmeans(model1, ~ invasiontreatment)
tukey_invasion <- pairs(emm_invasion, adjust = "tukey")
print("Tukey HSD results for invasiontreatment:")
print(tukey_invasion)
```
```{r Growth Tracking - Bindweed}
library(tidyverse)

data=read_csv("growthtracking.csv", na="?")
attach(data)
str(data)

temp.data <- subset(data, speciesid=="bindweed")
temp.data

temp.data2<-subset(temp.data,graphdate=="10-Jul")
temp.data2
#using this code to get the means and std error for the tables 
tempdata1 <- subset(temp.data2, treatment=="controluninvaded") 
tempdata1
mean(tempdata1$height_cm, na.rm=TRUE) 
std.error(tempdata1$height_cm, na.rm=TRUE)

shapiro.test(temp.data2$longestleaflength_cm)

model1<-lmer(longestleaflength_cm ~ shadetreatment*invasiontreatment + (1|potid), data = temp.data2)
model1 
Anova(model1,type="III")

# Perform Tukey HSD test for shadetreatment * invasiontreatment interaction
emm_interaction <- emmeans(model1, ~ shadetreatment * invasiontreatment)
tukey_interaction <- pairs(emm_interaction, adjust = "tukey")
print("Tukey HSD results for shadetreatment * invasiontreatment interaction:")
print(tukey_interaction)

# Perform Tukey HSD test for shadetreatment
emm_shade <- emmeans(model1, ~ shadetreatment)
tukey_shade <- pairs(emm_shade, adjust = "tukey")
print("Tukey HSD results for shadetreatment:")
print(tukey_shade)

# Perform Tukey HSD test for invasiontreatment
emm_invasion <- emmeans(model1, ~ invasiontreatment)
tukey_invasion <- pairs(emm_invasion, adjust = "tukey")
print("Tukey HSD results for invasiontreatment:")
print(tukey_invasion)

```
```{r Stepwise Regression - unused in thesis}
library(tidyverse)
library(lme4)
library(car)
library(effects)
library(MASS)

data=read_csv("growthtracking.csv", na="?")
attach(data)
str(data)

#Stepwise Regression 
 
temp.data <- subset(data, speciesid=="maple") 
temp.data 
df.summarylength <- temp.data %>%   
  group_by(potid, season, sampledate, shadetreatment, invasiontreatment) %>%   
  summarise(se = sd(longestleaflength_cm, na.rm = TRUE),     
                 longestleaflength = mean(longestleaflength_cm, na.rm = TRUE)   )
df.summarylength

#Stepwise Regression 
initial_model <- lm(longestleaflength ~ shadetreatment * invasiontreatment * season, data = df.summarylength)
final_model <- stepAIC(initial_model, direction = "both", trace = TRUE) 
 
# View the selected model - the lower the AIC the better the model 
summary(final_model) 
## Model comparisons - technically we saw no ranom effects is better but we can keep them in 
lmm_model1 <- lmer(longestleaflength ~ shadetreatment + invasiontreatment + season + (1 | potid), data = df.summarylength) 
###without effects is only slightly better, so lets keep the effects in 
lmm_model3 <- lm(longestleaflength ~ shadetreatment + invasiontreatment + season , data = df.summarylength) 
#Lower AIC is better model 
aic_bic <- data.frame(   Model = c("lmm_model1","lmm_model3"),   
                         AIC = AIC(lmm_model1, lmm_model3),   
                         BIC = BIC(lmm_model1,lmm_model3) ) 
print(aic_bic)
 
### Most parsimoneous model based on AICs - we added in the random effect here but it can also be removed to just have an lm model 
lmm_model <- lmer(longestleaflength ~  shadetreatment + invasiontreatment + season + (1 | potid), data = df.summarylength) 
summary(lmm_model) 
Anova(lmm_model,type = "III") 
 
##posthoc test of interaction pairwise differences - yikes! Looks scary right, dont worry, we can visualize this so its cleaner 
em_means <- emmeans(lmm_model, ~ shadetreatment*season) 
pairwise_comparisons <- pairs(em_means) 
summary(pairwise_comparisons) 
 
##Visualize #Visualizing the marginal effects can provide insights into the overall pattern of the interaction.
em_means <- emmeans(lmm_model, ~ shadetreatment*season) 
plot(em_means, comparisons = TRUE) 
 
# Create conditional effects plot 

#to change the organization of the interaction plots, change in the model
df.summarylength$shadetreatment <- factor(df.summarylength$shadetreatment, levels = c("early", "normal", "none"))
df.summarylength$season <- factor(df.summarylength$season, levels = c("early", "mid", "late"))

effect_plot <- plot(allEffects(lmm_model, xlevels = list(shadetreatment = c("early", "normal", "none"),
                                                         season = c("early", "mid", "late"))))
```
```{r Growth Tracking Linear Mixed Models w Random Effects - unused in thesis}

data=read_csv("growthtracking.csv", na="?")
attach(data)
str(data)
temp.data <- subset(data, speciesid=="hempnettle")
temp.data

hempnettledataf <- temp.data %>%
  group_by(potid, sampledate, shadetreatment, invasiontreatment, treatment, season ) %>%
  summarise(
    leaflength = mean(longestleaflength_cm, na.rm = TRUE),
    height = mean(height_cm, na.rm = TRUE),
    numberofleaves = mean(lognum_leaves, na.rm = TRUE)
    ) 
hempnettledataf

model.hempnettle.longest.leaf <- lmer(leaflength ~ shadetreatment + invasiontreatment + season + (1|potid), data = hempnettledataf)
qqnorm(resid(model.hempnettle.longest.leaf)) 
plot(model.hempnettle.longest.leaf)

model.hempnettle.height <- lmer(height ~ season +  shadetreatment*invasiontreatment + (1|potid), data = hempnettledataf)
qqnorm(resid(model.hempnettle.height)) 
plot(model.hempnettle.height)

model.hempnettle.numberleaves <- lmer(numberofleaves ~ season*shadetreatment*invasiontreatment + (1|potid), data = hempnettledataf)
qqnorm(resid(model.hempnettle.numberleaves)) 
plot(model.hempnettle.numberleaves)

leaflengthanova <- Anova(model.hempnettle.longest.leaf, type = "III")
leaflengthanova
heightanova <- Anova(model.hempnettle.height, type = "III")
heightanova
numberleavesanova <- Anova(model.hempnettle.numberleaves, type = "III")
numberleavesanova
 numberleavesemmeansshade <- emmeans(model.hempnettle.numberleaves, pairwise ~ shadetreatment, 
                                      adjust = "tukey")
  numberleavesemmeansshade

#means
hempmeansdata <- subset(temp.data, season=="late")
hempmeansdata

hempmeans <- hempmeansdata %>%
  group_by(shadetreatment, invasiontreatment ) %>%  
  summarise(     
    leaflength = mean(longestleaflength_cm, na.rm = TRUE),  
    leaflengthse = std.error(longestleaflength_cm, na.rm = TRUE),  
    height = mean(height_cm, na.rm = TRUE),  
    heightse = std.error(height_cm, na.rm = TRUE),
    numberofleaves = mean(num_leaves, na.rm = TRUE),
    numberofleavesse = std.error(num_leaves, na.rm = TRUE) 
    ) 
hempmeans

hempmeansinvasion <- hempmeansdata %>%
  group_by(invasiontreatment ) %>%  
  summarise(     
    leaflength = mean(longestleaflength_cm, na.rm = TRUE),  
    leaflengthse = std.error(longestleaflength_cm, na.rm = TRUE),  
    height = mean(height_cm, na.rm = TRUE),  
    heightse = std.error(height_cm, na.rm = TRUE),
    numberofleaves = mean(num_leaves, na.rm = TRUE),
    numberofleavesse = std.error(num_leaves, na.rm = TRUE) 
    ) 
hempmeansinvasion


hempmeansshade <- hempmeansdata %>%
  group_by(shadetreatment ) %>%  
  summarise(     
    leaflength = mean(longestleaflength_cm, na.rm = TRUE),  
    leaflengthse = std.error(longestleaflength_cm, na.rm = TRUE),  
    height = mean(height_cm, na.rm = TRUE),  
    heightse = std.error(height_cm, na.rm = TRUE),
    numberofleaves = mean(num_leaves, na.rm = TRUE),
    numberofleavesse = std.error(num_leaves, na.rm = TRUE) 
    ) 
hempmeansshade
```

